import { test, expect } from '@playwright/test';

test('Verify alert', async ({ page }) => {

  /* Handle alert as below */
  page.on('dialog', async (dialog) => {
    expect(await dialog.type()).toBe('alert');                 /* Type of dialog */
    expect(await dialog.message()).toBe('I am an alert box!'); /* Message of dialog */
    await dialog.accept();                                     /* Accept the alert */
  });

  const url: string = 'https://testautomationpractice.blogspot.com/';
  const expectedPageTitle: string = 'Automation Testing Practice';
  const alertButton = await page.locator('#alertBtn');

  await page.goto(url);

  await expect(page).toHaveTitle(expectedPageTitle);
  await expect(alertButton).toBeVisible().then(async () => {
      await alertButton.click();
      await page.waitForTimeout(5000); // Hard Wait for 5 seconds to observe the alert
  });

});

test('Verify Confirmation with OK', async ({ page }) => {

  page.on('dialog', async (dialog) => {
    expect(await dialog.type()).toBe('confirm');             /* Type of dialog */
    expect(await dialog.message()).toBe('Press a button!');  /* Message of dialog */
    await dialog.accept();   /* Closes confirmation with OK */
    // await dialog.dismiss();   /* Closes confirmation with Cancel */
  });

  const url: string = 'https://testautomationpractice.blogspot.com/';
  const expectedPageTitle: string = 'Automation Testing Practice';
  const confirmButton = await page.locator('#confirmBtn');

  await page.goto(url);

  await expect(page).toHaveTitle(expectedPageTitle);
  await expect(confirmButton).toBeVisible().then(async () => {
      await confirmButton.click();
  });

});

test('Verify Prompt dialogue with OK and some message', async ({ page }) => {

  page.on('dialog', async (dialog) => {
    expect(await dialog.type()).toBe('prompt');             /* Type of dialog */
    expect(await dialog.message()).toBe('Please enter your name:');  /* Message of dialog */
    expect(await dialog.defaultValue()).toBe('Harry Potter'); /* Default value in the prompt */

    await dialog.accept('INPUT MESSAGE');   /* Closing prompt with some input message */
    // await dialog.dismiss();   /* Closes prompt with Cancel */
  });

  const url: string = 'https://testautomationpractice.blogspot.com/';
  const expectedPageTitle: string = 'Automation Testing Practice';
  const promptButton = await page.locator('#promptBtn');

  await page.goto(url);

  await expect(page).toHaveTitle(expectedPageTitle);
  await expect(promptButton).toBeVisible().then(async () => {
      await promptButton.click();
      expect(await page.locator('p#demo')).toHaveText('Hello INPUT MESSAGE! How are you today?');
  });
});

test('Handling Basic authentication popup Way-1', async ({ page }) => {

  // We will add username and pwd directly in URL before domain name
  const url: string = 'https://admin:admin@the-internet.herokuapp.com/basic_auth';
  //                          ----------

  const authSuccessLocator = await page.locator('h3:has-text("Basic Auth")');

  await page.goto(url);
  await expect(authSuccessLocator).toBeVisible();
});

test('Handling Basic authentication popup Way-2', async ({ page }) => {

  /* In postman console we can see
    GET https://the-internet.herokuapp.com/basic_auth
    200
    253 ms
    Network
    Request Headers
    Authorization: Basic YWRtaW46YWRtaW4=
                  -----------------------
                  This is the token that is generated by encoding the username and password
                  It is generated by a common JS method btoa()

    User-Agent: PostmanRuntime/7.45.0 */

  const url: string = 'https://the-internet.herokuapp.com/basic_auth';
  const authSuccessLocator = await page.locator('h3:has-text("Basic Auth")');

  const username: string = 'admin';
  const password: string = 'admin';
  const authToken: string = 'Basic ' + btoa(`${username}:${password}`);

  await page.setExtraHTTPHeaders({
    'Authorization': authToken
  });

  await page.goto(url);
  await expect(authSuccessLocator).toBeVisible();
});

test.only('Configured Basic Authentication Way-3', async ({ page }) => {

  const url: string = 'https://the-internet.herokuapp.com/basic_auth';

  /* use: {

    httpCredentials: {
      username: 'admin',
      password: 'admin',
    }
  }, */

  const authSuccessLocator = await page.locator('h3:has-text("Basic Auth")');

  await page.goto(url);
  await expect(authSuccessLocator).toBeVisible();
});